// Generated by CoffeeScript 1.6.2
(function() {
  window.UiManager = (function() {
    function UiManager(a, b) {
      this.a = a;
      this.b = b;
    }

    return UiManager;

  })();

}).call(this);
